export {default as Footer}from './Footer/Footer'
export {default as Loginbutton}from './Loginbutton/Loginbutton'
export {default as Password}from './Password/Password'
export {default as Header}from './Header/Header'
export {default as Formtitleone}from './Formtitle/Formtitle'
export {default as Allbuttons}from './Allbuttons/Allbuttons'
export {default as Allfields}from './Allfields/Allfields'
export {default as Createpasswordpopup}from './Createpasswordpopup/Createpasswordpopup'