export {default as Landingpage} from './Landingpage/Landingpage.jsx'
export {default as Loginpage} from './Loginpage/Loginpage'
export {default as Profilepage} from './Profilepage/Profilepage.jsx'
export {default as Facultydashboard} from './Facultydashboard/Facultydashboard.jsx'
export {default as Registrationform} from './Registrationform/Registrationform.jsx'
export {default as Facultyregistration} from './Facultyregistration/Facultyregistration.jsx'